### ISSUE TITLE
Неправильная проверка типа

### ISSUE THREAD

**Issue by frontgirl** [gamlen/web-game-netology#7]
https://github.com/gamlen/web-game-netology/blob/de441ec04f388b9c38a5babd0e7843f4783f7bfd/game.js#L25

**Comment by frontgirl** [comment]
Вы откуда взяли такой синтаксис?

**Comment by gamlen** [comment]
метод же проверяет, к какому классу принадлежит объект, и если не один из них не наследует класс, то делает код по условию

**Comment by frontgirl** [comment]
Откуда этот метод в классе Vector? Где вы его объявляете?

**Comment by gamlen** [comment]
Принимает три аргумента: расположение, объект типа Vector, размер, тоже объект типа Vector и скорость, тоже объект типа Vector.

**Comment by gamlen** [comment]
Если в качестве первого, второго или третьего аргумента передать не объект типа Vector, то конструктор должен бросить исключение.

**Comment by frontgirl** [comment]
Я вижу в классе Vector конструктор, метод plus и метод times. Подскажите, где объявлен метод instanceOf? сейчас в классе Vector такого метода нет. Следовательно, при попытке вызова location.instanceOf(Vector) возникает ошибка - попытка обратиться к несуществующему свойству.
