### ISSUE TITLE
Не сработает, если в конструктор не передан параметр grid

### ISSUE THREAD

**Issue by frontgirl** [gamlen/web-game-netology#8]
https://github.com/gamlen/web-game-netology/blob/de441ec04f388b9c38a5babd0e7843f4783f7bfd/game.js#L63

**Comment by gamlen** [comment]
Попробуйте сейчас посмотреть

**Comment by gamlen** [comment]
опубликую

**Comment by frontgirl** [comment]
Здесь нужно задать параметр по умолчанию, то есть, задать некое значение, которое примет grid, в случае если мы не передали этот параметр в конструкторе. Параметры по умолчанию рассматривались в разделе, посвященному функциям в js.

**Comment by gamlen** [comment]
Да, параметр обозначен, возможно я не обновил файл.
Готово
