### ISSUE TITLE
Нельзя называть параметры с большой буквы

### ISSUE THREAD

**Issue by frontgirl** [gamlen/web-game-netology#9]
https://github.com/gamlen/web-game-netology/blob/de441ec04f388b9c38a5babd0e7843f4783f7bfd/game.js#L49

**Comment by frontgirl** [comment]
Мы используем camelCase на проекте. Все правила оформления кода https://netology-university.bitbucket.io/codestyle/javascript/

**Comment by gamlen** [comment]
Готово
